### ISSUE TITLE
Does not camelize right in case of upper case characters in an underscored property

### ISSUE THREAD

**Issue by skgnair** [tlivings/camelscore#2]
Example:

`is_2FA_login` when camelized becomes `is2FA_login` and not `is2FALogin`

**Comment by tlivings** [comment]
Sort of fixed but not completely. There is no way to determine (that I can think of) how `is2FALogin` should be snake_cased. It will wind up as `is_2_f_a_login`. 

However, `is_2FA_login` will camelCase properly.
