### ISSUE TITLE
Any licensing? 

### ISSUE THREAD

**Issue by andresilveirah** [tlivings/camelscore#5]
Hey @tlivings I've copied the `underscorify` part of your code and used in a commercial project. Is it alright?

**Comment by andresilveirah** [comment]
In the end, I changed the code so much that I think the question no longer makes sense.

**Comment by tlivings** [comment]
Well, to answer your question - you can do whatever you want with it. Copy it, use it for commercial purposes - it's really rather trivial code. I just created it for reusability.

**Comment by andresilveirah** [comment]
Cool, thanks!
For the record, here's my version https://gist.github.com/andresilveira/a6a4f4cede8f41cda6bfaaae5234edf2
